# Generated by Django 5.2.17 on 2026-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_bio_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_cr',
            field=models.BooleanField(default=False, help_text='CRs can book rooms and post/update class and lab notices. Granted by an admin from the admin panel.', verbose_name='Class Representative (CR)'),
        ),
    ]
