# Generated by Django 5.2.17 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_is_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_librarian',
            field=models.BooleanField(default=False, help_text="Librarians can add, upload and update the library's book list. Granted by an admin from the admin panel.", verbose_name='Librarian'),
        ),
    ]
