# Generated by Django 5.2.17 on 2026-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_club_member',
            field=models.BooleanField(default=False, help_text='Club Members can post and update Club notices, including images and links. Granted by an admin from the admin panel.', verbose_name='Club Member'),
        ),
    ]
