# Generated by Django 5.2.17 on 2026-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_is_club_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_route',
            field=models.CharField(blank=True, choices=[('farmgate', 'Farmgate to NITER'), ('gabtoli', 'Gabtoli to NITER'), ('uttara', 'Uttara to NITER')], help_text='The bus route this driver is assigned to (drivers only).', max_length=20, null=True, verbose_name='Assigned route'),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('driver', 'Driver')], default='student', help_text='Drivers can share their live bus location from the Bus Tracker. Granted by an admin from the admin panel.', max_length=20, verbose_name='Role'),
        ),
    ]
