# Generated by Django 5.2.17 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_student_assigned_route_student_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cr", "CR (Class Representative)"),
                            ("club_member", "Club Member"),
                            ("librarian", "Librarian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "CSE"),
                            ("EEE", "EEE"),
                            ("TE", "TE"),
                            ("IPE", "IPE"),
                            ("FDAE", "FDAE"),
                        ],
                        help_text="The department this person belongs to.",
                        max_length=10,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text=(
                            "The student's NIT ID — must exactly match the ID on "
                            "their profile."
                        ),
                        max_length=50,
                        verbose_name="Student ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role", "full_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="rolecredential",
            constraint=models.UniqueConstraint(
                fields=("role", "full_name", "department", "student_id"),
                name="unique_role_credential",
            ),
        ),
    ]
