# Generated by Django 5.2.17 on 2026-08-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('floor', models.PositiveSmallIntegerField()),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
                'constraints': [models.UniqueConstraint(fields=('building', 'floor', 'room_number'), name='unique_room')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('class_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='rooms.room')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
