# Generated by Django 5.2.17 on 2026-08-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='end_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='start_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entry', to='rooms.roombooking'),
        ),
    ]
