# Generated by Django 5.2.17 on 2026-08-10 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roombooking_end_time_roombooking_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
