# Generated by Django 5.2.17 on 2026-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roombooking_date_scheduleentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='day',
            field=models.CharField(blank=True, choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
