# Generated by Django 5.2.17 on 2026-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('TE', 'TE'), ('IPE', 'IPE'), ('FDAE', 'FDAE')], default='', max_length=10),
        ),
    ]
