# Generated by Django 5.2.17 on 2026-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_image_notice_link_label_notice_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice_files/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
