from django.conf import settings
from django.db import models

from accounts.models import DEPARTMENTS


class LabReport(models.Model):
    """A saved lab report cover page generated by a student.

    Any signed-in student (except Librarians and Drivers — the frontend hides
    the page for them) can create and manage their own cover pages. The fields
    mirror the NITER lab report cover sheet: course details on top, then the
    Submitted By (the student) and Submitted To (the course teacher) blocks.
    ``student_name`` / ``student_id`` come from the student's own profile at
    save time so the cover always shows their real details.
    """

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="lab_reports",
    )
    # The student's department for this report (prefilled from the profile,
    # editable on the form — the report is a snapshot, not a live link).
    department = models.CharField(
        max_length=10,
        choices=[(dept, dept) for dept in DEPARTMENTS],
    )

    # Course details.
    course_title = models.CharField(max_length=200)
    course_code = models.CharField(max_length=50)
    date_of_submission = models.DateField()
    experiment_name = models.CharField(max_length=300)
    remarks = models.CharField(max_length=300, blank=True, default="")

    # Submitted By — the student. Prefilled from the profile, stored as a
    # snapshot so past reports keep the details they were saved with.
    # (``student_id`` is a plain CharField — the FK is named ``owner``.)
    student_name = models.CharField(max_length=100)
    student_id = models.CharField(max_length=50)
    section = models.CharField(max_length=20)
    level_term = models.CharField(max_length=20)
    session = models.CharField(max_length=20)

    # Submitted To — the course teacher.
    teacher_name = models.CharField(max_length=100)
    teacher_rank = models.CharField(max_length=100, blank=True, default="")
    teacher_department = models.CharField(
        max_length=10,
        choices=[(dept, dept) for dept in DEPARTMENTS],
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.course_code}: {self.experiment_name}"
