# Generated by Django 5.2.17 on 2026-08-14 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('TE', 'TE'), ('IPE', 'IPE'), ('FDAE', 'FDAE')], max_length=10)),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=50)),
                ('date_of_submission', models.DateField()),
                ('experiment_name', models.CharField(max_length=300)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=20)),
                ('level_term', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_rank', models.CharField(blank=True, default='', max_length=100)),
                ('teacher_department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('TE', 'TE'), ('IPE', 'IPE'), ('FDAE', 'FDAE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
