# Generated by Django 5.2.17 on 2026-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(choices=[('farmgate', 'Farmgate to NITER'), ('gabtoli', 'Gabtoli to NITER'), ('uttara', 'Uttara to NITER')], max_length=20, unique=True, verbose_name='Route')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['route'],
            },
        ),
    ]
