# Generated by Django 5.2.17 on 2026-08-09 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Documents', 'Documents'), ('Others', 'Others')], default='Others', max_length=20)),
                ('description', models.TextField()),
                ('location_found', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_found/')),
                ('finder_name', models.CharField(max_length=100)),
                ('finder_phone', models.CharField(max_length=30)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted', '-id'],
            },
        ),
    ]
