# Generated by Django 5.2.17 on 2026-08-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founditem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
